name: Integration

on:
  pull_request:
    branches: [main]

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Poetry 🎵
        run: pipx install poetry

      - name: Setup Python 🐍
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "poetry"

      - name: Setup Scripts 🧩
        run: |
          poetry install
          poetry run inv env.switch ci
          poetry run inv tool.install ci-int --yes

      - name: Lint 🪶
        run: poetry run inv lint

      - name: Test 🧪
        run: poetry run inv test
