name: Publication

on:
  push:
    branches: [main]

jobs:
  publication:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Git ✨
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Setup Poetry 🎵
        run: pipx install poetry

      - name: Setup Python 🐍
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "poetry"

      - name: Setup Scripts 🧩
        run: |
          poetry install
          inv env.switch ci
          inv tool.install ci-dep --yes

      - name: Build 🏗️
        run: inv build

      - name: Publish 🚀
        run: inv publish
